---
apiVersion: v1
kind: Secret
type: Opaque
namespace: monitoring
metadata:
    name: elasticsearch-pw-kibana
    labels: {}
stringData:
    ELASTICSEARCH_USERNAME: "kibana"
    ELASTICSEARCH_PASSWORD: "${KIBANA_PASS}"

---
apiVersion: v1
kind: Secret
type: Opaque
namespace: monitoring
metadata:
    name: elasticsearch-pw-beats
    labels: {}
stringData:
    ELASTICSEARCH_USERNAME: "beats_system"
    ELASTICSEARCH_PASSWORD: "${BEATS_PASS}"

---
apiVersion: v1
kind: Secret
type: Opaque
namespace: kube-system
metadata:
    name: elasticsearch-pw-elastic
    labels: {}
stringData:
    ELASTICSEARCH_USERNAME: "elastic"
    ELASTICSEARCH_PASSWORD: "${ELASTIC_PASS}"

---
