---
kind: Service
apiVersion: v1
metadata:
  name: ${CICD_IMAGE}-service
spec:
  selector:
    app: ${CICD_IMAGE}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80