---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${CICD_IMAGE}
  namespace: default
  labels:
    app: ${CICD_IMAGE}
spec:
  serviceName: ${CICD_IMAGE}
  replicas: 3
  selector:
    matchLabels:
      app: ${CICD_IMAGE}
  template:
    metadata:
      labels:
        app: ${CICD_IMAGE}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: ${CICD_IMAGE}
      serviceAccountName: ${CICD_IMAGE}
      containers:
        - name: ${CICD_IMAGE}
          # image: gcr.io/{{project}}/{{service}}:{{tag}}
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80  